version: '2'
services:
    nginx:
        image: nginx
        container_name: Nginx
        restart: always
        depends_on:
            - python
        ports:
            - '80:80'
            - '443:443'
        volumes:
            # - /etc/localtime:/etc/localtime
            - ./Nginx/log/:/var/log/nginx/
            - ./Nginx/cfg/:/etc/nginx/conf.d/
            - ./Nginx/letsencrypt/:/etc/letsencrypt/
            - ./Projects/:/srv/
    python:
        build:
            context: .
            dockerfile: dockerfile_python
        container_name: Python
        command: ['/bin/bash', '/home/boot.sh']
        restart: always
        depends_on:
            - mysql
        ports:
            - '5000:5000'
        volumes:
            # - /etc/localtime:/etc/localtime
            - ./Projects/:/srv/
            - ./Nginx/log/:/var/log/uwsgi/
        tty: true
