version: '2'
services:
    nginx:
        image: nginx
        container_name: Nginx
        restart: always
        depends_on:
            - python
        ports:
            - '80:80'
            - '443:443'
        volumes:
            # - /etc/localtime:/etc/localtime
            - ./Nginx/log/:/var/log/nginx/
            - ./Nginx/cfg/:/etc/nginx/conf.d/
            - ./Nginx/letsencrypt/:/etc/letsencrypt/
            - ./Projects/:/srv/
    mysql:
        image: mysql:5.7
        # image: hypriot/rpi-mysql
        container_name: MySQL
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        volumes:
            # - /etc/localtime:/etc/localtime
            - ./MySQL/conf:/etc/mysql/conf.d
            - ./MySQL/database/:/var/lib/mysql/
            - ./MySQL/log/:/var/log/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PWD}"
    # redis:
    #     image: redis:3.2
    #     container_name: Redis
    #     command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PWD}"]
    #     restart: always
    #     ports:
    #         - '6379:6379'
    #     volumes:
    #           # - /etc/localtime:/etc/localtime
    #         - ./Redis/:/data/
    python:
        build:
            context: .
            dockerfile: dockerfile_python
        container_name: Python
        command: ['/bin/bash', '/home/boot.sh']
        restart: always
        depends_on:
            - mysql
        ports:
            - '5000:5000'
        volumes:
            # - /etc/localtime:/etc/localtime
            - ./Projects/:/srv/
            - ./Nginx/log/:/var/log/uwsgi/
        tty: true
